## The makeCacheMatrix() creates a special "vector"(a list) that cache the inverse of a matrix. By using aMatrix <- makeCacheMatrix(x) as its argument, the CacheSolve() function can retrieve the cached inverse matrix if already assigned. If he inverse has not yet been assigned, cacheSolve() computes it and assigns it to x.

## The makeCacheMatrix() function creates a list of 4 functions: set(); get(); setinv();getinv()(comment on these functions below).


makeCacheMatrix <- function(x = matrix()) { #we assign a default argument
        inv <- NULL                         #this initializes the object inv by assigning to it the null object
        set <- function(y){                 #this functions assign a value y to x in the parent environment and the null value to the inv object in the parent environment
                x <<- y                       
                inv <<- NULL                  
        }
        get <- function() x                 #the get() function returns x
        setinv <- function(inverse) inv<<- inverse  #the setinv() function assigns an object (a matrix) to the inv object in the parent environment 
        getinv <- function() inv              # the getinv() return the inv object
        list(set=set, get=get, setinv=setinv, getinv=getinv) #this returns the list of the four functions with their names

}


## The cacheSolve() function does one of two things conditional on whether the inverse function has been assigned (see below for furhter comments).

cacheSolve <- function(x, ...) {
        inv <- x$getinv() #it assigns to inv the value of geninv() subsetted from the list generated by makeCacheMatrix
        if(!is.null(inv)){ #if is.null(inv) = FALSE (if the inverse functions has been assigned), then it retrieves the cached value and it displays a message to signal that the value has been cached)
                message("getting cached data")
                return(inv)
        }
        data <- x$get() #if is.null(inv)=TRUE, then it assigns to the new object called "data" the value of the matrix by subsetting from the list in makeCacheMatrix
        inv <- solve(data, ...) #then it assigns to inv the value of the inverse of x using the sove() function
        x$setinv(inv) #finally is cache the value 'inverse' to the object 'inv' using the subsetted funtion 'setinv()'
        inv ## it returns a matrix that is the inverse of 'x'
}
